### ISSUE TITLE
Renew Eventbrite Tickets

### ISSUE THREAD

**Issue by halfempty** [santacruzmah/santacruzmah#54]
@elisegranata, question for you:

Are we still actively using Eventbrite Tickets with Events? We have a plugin to a plugin that enables them, but I only want to renew it if we're using it.

**Comment by elisegranata** [comment]
Yes, twice per year-- for GLOW and Red Ball. We typically just embed the
Eventbrite ticket code into the page...do we need a plugin in order to do
that?

On Tue, Dec 1, 2015 at 9:35 AM, Marty Spellerberg <notifications@github.com>
wrote:

> @elisegranata <https://github.com/elisegranata>, question for you:
>
> Are we still actively using Eventbrite Tickets with Events? We have a
> plugin to a plugin that enables them, but I only want to renew it if we're
> using it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/santacruzmah/santacruzmah/issues/54>.
>



-- 
Like what we do? Help us thrive – become a MAH member today
<http://join.santacruzmah.org/>.

*Elise Granata*
*Marketing & Engagement Coordinator*
*Santa Cruz Museum of Art & History*
*705 Front Street | Santa Cruz | CA 95060*

*831.429.1964 ext 7028*
Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
<http://www.facebook.com/santacruzmah>.

*Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
change on event days)


*Get to the MAH this month. Here's what's coming up:*
3rd Friday: Radical Craft Night (Nov 20th)
<http://www.santacruzmah.org/event/3rd-friday-radical-craft-2/>
FREE First Friday: Wild Mushrooms & Functional Fungi Opening (Dec 4th)
<http://www.santacruzmah.org/event/free-first-friday-31/>
3rd Friday: Winterpalooza (Dec 18th)
<http://www.santacruzmah.org/event/winterpalooza-2/>

**Comment by halfempty** [comment]
Okay, I've disabled the plugin. We just won't use it.
